// <auto-generated>
//     Swarm → Audio → Rebuild 가 만든 파일이다. 손으로 고치지 말 것 — 다음 재생성에 사라진다.
//     원본: Assets/StreamingAssets/Audio/GeneratedSoundBanks/<플랫폼>/*.json
//     생성기: Assets/_Project/Scripts/Editor/WwiseIdGenerator.cs
// </auto-generated>

namespace Swarm.Audio
{
    /// <summary>
    /// 사운드뱅크가 실제로 담고 있는 이름과 ID. 게임 코드가 Wwise를 부를 때 쓰는 유일한 이름 출처다.
    /// 문자열로 부르면 오타가 런타임에 조용히 실패하므로 상수로 굳혀 컴파일 에러가 되게 한다.
    /// </summary>
    public static class WwiseIds
    {
        /// <summary>이벤트.</summary>
        public static class Events
        {
            public const uint Play_Music = 2932040671u;
            public const uint Play_Object_Pickup = 2818358958u;
            public const uint Play_XP_Pickup = 1598016745u;
            public const uint Stop_Music = 2837384057u;
        }

        /// <summary>Game Parameter(RTPC).</summary>
        public static class Rtpc
        {
            public const uint Enemy_Count = 799803063u;
            public const uint Music_Pitch = 4079200817u;
            public const uint Player_Health = 215992295u;
            public const uint Volume_Music = 3891337659u;
            public const uint Volume_SFX = 3673881719u;
        }

        /// <summary>State 그룹과 그 아래 상태들.</summary>
        public static class States
        {
            public static class Game_State
            {
                public const uint Group = 766723505u;
                public const uint Dead = 2044049779u;
                public const uint LevelUp = 1994668398u;
                public const uint None = 748895195u;
                public const uint Playing = 1852808225u;
                public const uint Title = 3705726509u;
            }
        }

        /// <summary>사운드뱅크 이름. 로드는 이름으로 한다.</summary>
        public static class Banks
        {
            public const string Init = "Init";
            public const string Main = "Main";
        }
    }
}
